services:
  database:
    container_name: database
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,dynamodb
    #      - DEFAULT_REGION=us-east-1
    #      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      # This is called when Localstack container is starting up.
      # Using this for AWS CLI commands currently.
      - ./database/init-scripts/init-localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
      - ./database/init-scripts/dynamodb-table-definition.json:/opt/code/localstack/dynamodb-table-definition.json