openapi: 3.0.0
info:
  title: Client REST API
  version: 1.0
paths:
  /clients:
    get:
      parameters:
        - name: x-api-version
          in: header
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"

components:
  schemas:
    Client:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
