openapi: 3.0.0
info:
  title: Clients REST API
  version: "1.0"
paths:
  /clients:
    parameters:
      - $ref: "shared.yaml#/components/headers/X-Api-Version"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
        '5XX':
          description: Server error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        '5XX':
          description: Server Error
  /clients/{clientId}:
    parameters:
      - $ref: "shared.yaml#/components/headers/X-Api-Version"
      - $ref: "#/components/parameters/ClientId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        '5XX':
          description: Server Error
    delete:
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error

components:
  schemas:
    Client:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
  parameters:
    ClientId:
      in: path
      name: clientId
      required: true
      schema:
        type: string


