openapi: 3.0.0
info:
  title: Client REST API
  version: 1.0
paths:
  /clients:
    get:
      parameters:
        - name: x-api-version
          in: header
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Location:
      allOf:
        - $ref: "generic.yaml#/components/schemas/Base"
    Organizer:
      allOf:
        - $ref: "generic.yaml#/components/schemas/Base"
    Event:
      allOf:
        - $ref: "generic.yaml#/components/schemas/Base"
        - properties:
            eventType:
              $ref: "generic.yaml#/components/schemas/EventType"



