openapi: 3.0.0
info:
  title: Clients REST API
  version: "1.0"
paths:
  /clients:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: "#/components/schemas/Client"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/Client"
        '5XX':
          description: Server Error

components:
  schemas:
    Client:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      properties:
        clientId:
          type: string
