openapi: 3.0.0
info:
  title: Client REST API
  version: 1.0
paths:
  /clients:
    get:
      parameters:
        - name: x-api-version
          in: header
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
#    Base:
#      type: object
    Taco:
      type: object
      properties:
        clientId:
          type: string
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time
      required:
        - clientId
        - createdOn
        - lastUpdatedOn