openapi: 3.0.0
info:
  title: Client REST API
  version: 1.0
paths:
  /clients:
    get:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: array
                  $ref: "#/components/schemas/Client"
  /clients/{clientId}:
    get:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
        - name: clientId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"

components:
  schemas:
    Client:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
