openapi: 3.0.0
info:
  title: Events REST API
  version: "1.0"
servers: [ ]
paths:
  /clients/{clientId}/events:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
    get:
      operationId: getEvents
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
        '5XX':
          description: Server error
    post:
      operationId: postEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        '5XX':
          description: Server Error
  /clients/{clientId}/events/{eventId}:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
      - $ref: "#/components/parameters/EventId"
    get:
      operationId: getEventById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        '5XX':
          description: Server Error
    delete:
      operationId: deleteEventById
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error
components:
  schemas:
    Event:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - clientId
      properties:
        clientId:
          type: string
        eventId:
          type: string
        locationId:
          type: string
        organizerId:
          type: string
        description:
          type: string
        category:
          type: string
  parameters:
    EventId:
      in: path
      name: eventId
      required: true
      schema:
        type: string
