openapi: 3.0.0
info:
  title: Health REST API
  version: "1.0"
servers: [ ]
paths:
  /health:
    get:
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '5XX':
          description: Server error