openapi: 3.0.0
info:
  title: Health REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /actuator/health:
    get:
      operationId: getHealth
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '5XX':
          description: Server error