openapi: 3.0.0
info:
  title: Locations REST API
  version: "1.0"
paths:
  /clients/{clientId}/locations:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
        '5XX':
          description: Server error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        '5XX':
          description: Server Error
  /clients/{clientId}/locations/{locationId}:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
      - $ref: "#/components/parameters/LocationId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        '5XX':
          description: Server Error
    delete:
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error

components:
  schemas:
    Location:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - clientId
      properties:
        clientId:
          type: string
        locationId:
          type: string
  parameters:
    LocationId:
      in: path
      name: locationId
      required: true
      schema:
        type: string

