openapi: 3.0.0
info:
  title: Locations REST API
  version: "1.0"
paths:
  /locations:
    get:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
        '5XX':
          description: Server error
    post:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        '5XX':
          description: Server Error
  /locations/{locationId}:
    get:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
        - $ref: "#/components/parameters/LocationId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        '5XX':
          description: Server Error
    delete:
      parameters:
        - $ref: "shared.yaml#/components/parameters/ApiVersion"
        - $ref: "#/components/parameters/LocationId"
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error

components:
  schemas:
    Location:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
  parameters:
    LocationId:
      in: path
      name: locationId
      required: true
      schema:
        type: string
