openapi: 3.0.0
info:
  title: Scheduled Events REST API
  version: "1.0"
paths:
  /clients/{clientId}/scheduled-events:
    parameters:
      - $ref: "shared.yaml#/components/headers/X-Api-Version"
      - $ref: "client.yaml#/components/parameters/ClientId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduledEvent"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server Error
  /clients/{clientId}/scheduled-events/{scheduledEventId}:
    parameters:
      - $ref: "shared.yaml#/components/headers/X-Api-Version"
      - $ref: "client.yaml#/components/parameters/ClientId"
      - $ref: "#/components/parameters/ScheduledEventId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server Error
    delete:
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error
components:
  schemas:
    ScheduledEventType:
      type: string
      enum:
        - SINGLE
        - REOCCURRING
    ScheduledEventInterval:
      type: string
      enum:
        - DAILY
        - WEEKLY
        - BIWEEKLY
        - MONTHLY
        - WEEKDAYS
        - WEEKENDS
    ScheduledEventDay:
      type: string
      enum:
        - MON
        - TUE
        - WED
        - THU
        - FRI
        - SAT
        - SUN
    Cost:
      type: integer

    ScheduledEvent:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      properties:
        scheduledEventId:
          type: string
        locationId:
          type: string
          description: Override the default event location id
        organizerIds:
          type: array
          items:
            type: string
          description: Override the default event organizer id(s)
        cost:
          type: integer
          description: Cost of event in pennies
  parameters:
    ScheduledEventId:
      in: path
      name: eventId
      required: true
      schema:
        type: string
