openapi: 3.0.0
info:
  title: Scheduled Events REST API
  version: "1.0"
paths:
  /event-schedules/{eventScheduleId}/scheduled-events:
    parameters:
      - $ref: "event-schedule.yaml#/components/parameters/EventScheduleId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduledEvent"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server Error
  /event-schedules/{eventScheduleId}/scheduled-events/{scheduledEventId}:
    parameters:
      - $ref: "event-schedule.yaml#/components/parameters/EventScheduleId"
      - $ref: "#/components/parameters/ScheduledEventId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledEvent"
        '5XX':
          description: Server Error
    delete:
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error
components:
  schemas:
    ScheduledEventType:
      type: string
      enum:
        - SINGLE
        - REOCCURRING
    ScheduledEventInterval:
      type: string
      enum:
        - DAILY
        - WEEKLY
        - WEEKDAYS
        - WEEKENDS
    ScheduledEventDay:
      type: string
      enum:
        - MON
        - TUE
        - WED
        - THU
        - FRI
        - SAT
        - SUN
    ScheduledEvent:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - eventScheduleId
        - clientId
        - eventId
        - scheduledEventType
        - startTime
        - endTime
      properties:
        eventScheduleId:
          type: string
        scheduledEventId:
          type: string
        clientId:
          type: string
        eventId:
          type: string
        locationId:
          type: string
        organizerIds:
          type: array
          items:
            type: string
        scheduledEventType:
          $ref: "#/components/schemas/ScheduledEventType"
        scheduledEventInterval:
          $ref: "#/components/schemas/ScheduledEventInterval"
        scheduledEventDay:
          $ref: "#/components/schemas/ScheduledEventDay"
        description:
          type: string
        category:
          type: string
        startTime:
          type: string
          format: local-time
          example: "13:02:34"
        endTime:
          type: string
          format: local-time
          example: "13:02:34"
        scheduledEventDate:
          type: string
          format: local-date
          example: "2019-05-17"
        cost:
          type: integer
          description: Cost of event in pennies
  parameters:
    ScheduledEventId:
      in: path
      name: scheduledEventId
      required: true
      schema:
        type: string
