openapi: 3.0.0
info:
  title: Shared Classes
  version: "1.0"
paths:

components:
  schemas:
    Base:
      type: object
      properties:
        clientId:
          type: string
        name:
          type: string
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time
      required:
        - name
  headers:
    X-Api-Version:
      schema:
        type: integer
        default: 1