openapi: 3.0.0
info:
  title: Shared Classes
  version: "1.0"
servers: [ ]
paths:
  /actuator/health:
    get:
      responses:
        200:
          description: OK

components:
  schemas:
    Base:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time