openapi: 3.0.0
info:
  title: Shared Classes
  version: "1.0"
paths:

components:
  schemas:
    Base:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time