openapi: 3.0.0
info:
  title: Shared Classes
  version: "1.0"
paths:

components:
  schemas:
    Base:
      type: object
      properties:
        clientId:
          type: string
        name:
          type: string
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time
      required:
        - name
  parameters:
    ApiVersion:
      in: header
      name: x-api-version
      required: false
      schema:
        type: integer
        default: 1