openapi: 3.0.0
info:
  title: Users REST API
  version: "1.0"
paths:
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/User"
        '5XX':
          description: Server Error
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /users/{userId}:
    parameters:
      - $ref: "#/components/parameters/UserId"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '5XX':
          description: Server Error
components:
  schemas:
    User:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      properties:
        userId:
          type: string
        clientIds:
          type: array
          items:
            type: string
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      schema:
        type: string
