openapi: 3.0.0
info:
  title: Establishments REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /establishments:
    post:
      operationId: postEstablishments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Establishment"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Establishment"
        '5XX':
          description: Server Error
    get:
      operationId: getEstablishments
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Establishment"
  /establishments/{establishmentId}:
    parameters:
      - $ref: "#/components/parameters/EstablishmentId"
    get:
      operationId: getEstablishmentById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Establishment"
        '5XX':
          description: Server Error

components:
  schemas:
    Establishment:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      properties:
        establishmentId:
          type: string
  parameters:
    EstablishmentId:
      in: path
      name: establishmentId
      required: true
      schema:
        type: string
