openapi: 3.0.0
info:
  title: Event Schedules REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /clients/{clientId}/event-schedules:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
    get:
      operationId: getEventSchedules
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventSchedule"
        '5XX':
          description: Server error
    post:
      operationId: postEventSchedules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/EventSchedule"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventSchedule"
        '5XX':
          description: Server Error
  /clients/{clientId}/event-schedule/{eventScheduleId}:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
      - $ref: "#/components/parameters/EventScheduleId"
    get:
      operationId: getEventScheduleById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventSchedule"
        '5XX':
          description: Server Error
    delete:
      operationId: deleteEventScheduleById
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error
components:
  schemas:
    EventSchedule:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - clientId
      properties:
        clientId:
          type: string
        eventScheduleId:
          type: string
        description:
          type: string
  parameters:
    EventScheduleId:
      in: path
      name: eventScheduleId
      required: true
      schema:
        type: string
