openapi: 3.0.0
info:
  title: Events REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /establishments/{establishmentId}/files/{filename}:
    parameters:
      - $ref: "establishment.yaml#/components/parameters/EstablishmentId"
      - $ref: "#/components/parameters/Filename"
    get:
      operationId: getFileByFilename
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '5XX':
          description: Server Error
components:
  parameters:
    Filename:
      in: path
      name: filename
      required: true
      schema:
        type: string
