openapi: 3.0.0
info:
  title: Organizers REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /establishments/{establishmentId}/organizers:
    parameters:
      - $ref: "establishment.yaml#/components/parameters/EstablishmentId"
    get:
      operationId: getOrganizers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Organizer"
        '5XX':
          description: Server error
    post:
      operationId: postUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Organizer"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organizer"
        '5XX':
          description: Server Error
  /establishments/{establishmentId}/organizers/{organizerId}:
    parameters:
      - $ref: "establishment.yaml#/components/parameters/EstablishmentId"
      - $ref: "#/components/parameters/OrganizerId"
    get:
      operationId: getOrganizerById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organizer"
        '5XX':
          description: Server Error
    delete:
      operationId: deleteOrganizerById
      responses:
        204:
          description: The resource was deleted successfully.
        '5XX':
          description: Server Error

components:
  schemas:
    Organizer:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - establishmentId
      properties:
        establishmentId:
          type: string
        organizerId:
          type: string
  parameters:
    OrganizerId:
      in: path
      name: organizerId
      required: true
      schema:
        type: string
