openapi: 3.0.0
info:
  title: Published Event Schedules REST API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /clients/{clientId}/published-event-schedules:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
    get:
      operationId: getEventSchedules
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PublishedEventSchedule"
        '5XX':
          description: Server error
    post:
      operationId: postEventSchedules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublishedEventSchedule"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PublishedEventSchedule"
        '5XX':
          description: Server Error
  /clients/{clientId}/published-event-schedules/{publishedEventScheduleId}:
    parameters:
      - $ref: "client.yaml#/components/parameters/ClientId"
      - $ref: "#/components/parameters/PublishedEventScheduleId"
    get:
      operationId: getEventScheduleById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishedEventSchedule"
        '5XX':
          description: Server Error

components:
  schemas:
    PublishedEventSchedule:
      allOf:
        - $ref: "shared.yaml#/components/schemas/Base"
      required:
        - clientId
        - eventScheduleId
        - targetYear
        - targetMonth
      properties:
        clientId:
          type: string
        publishedEventScheduleId:
          type: string
        eventScheduleId:
          type: string
        targetYear:
          type: integer
        targetMonth:
          type: integer
        filename:
          type: string
  parameters:
    PublishedEventScheduleId:
      in: path
      name: publishedEventScheduleId
      required: true
      schema:
        type: string

