openapi: 3.0.0
info:
  title: Shared Classes
  version: "1.0"
servers:
  - url: http://localhost:8080
paths: { }
components:
  schemas:
    Base:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
        createdOn:
          type: string
          format: date-time
        lastUpdatedOn:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
            example: "Something went wrong"