name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  Deploy-Prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      # Instead of rebuilding, we need to "promote" to releases
      # - name: Set up JDK 17 for x64
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: "17"
      #     distribution: "corretto"
      #     cache: "maven"
      # - name: Build and Package Docker
      #   run: mvn package -Dpackaging=docker
