name: Pull Request
on:
  pull_request:
    branches:
      - main
      - release/conversion-spring

jobs:
  Pull-Request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"

      - name: Build Application
        run: mvn clean package
